### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by umbriquse** [relinc/SurePulse#67]
```
C:\Users\Jason\AppData\Roaming\RELFX\DataProc\Result\ncorr_job_file.txt
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at net.relinc.correlation.controllers.DICSplashpageController.renderResultsImages(DICSplashpageController.java:1501)
        at net.relinc.correlation.controllers.DICSplashpageController.notifyGuiDicFinished(DICSplashpageController.java:1803)
        at net.relinc.correlation.controllers.DICSplashpageController$29$3.run(DICSplashpageController.java:1776)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
```

**Comment by markhalonen** [comment]
I had to install https://www.microsoft.com/en-us/download/details.aspx?id=48145 on a 64 bit Windows computer to get ncorr working
